image: registry.gitlab.com/lingrino/docker/docker:latest

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375/

before_script:
  - docker login -u ${CI_REGISTRY_USER} -p ${CI_JOB_TOKEN} ${CI_REGISTRY}

stages:
  - lint
  - build
  - publish

##########################
### CI                 ###
##########################
lint-ci:
  stage: lint
  script:
    - hadolint ci.Dockerfile

build-ci:
  stage: build
  script:
    - docker pull ${CI_REGISTRY_IMAGE}/ci:latest || true
    - docker build --cache-from ${CI_REGISTRY_IMAGE}/ci:latest -t ${CI_REGISTRY_IMAGE}/ci:${CI_COMMIT_SHA} -f ci.Dockerfile .
    - docker push ${CI_REGISTRY_IMAGE}/ci:${CI_COMMIT_SHA}

publish-ci:
  stage: publish
  only: [ master ]
  script:
    - docker pull ${CI_REGISTRY_IMAGE}/ci:${CI_COMMIT_SHA}
    - docker tag ${CI_REGISTRY_IMAGE}/ci:${CI_COMMIT_SHA} ${CI_REGISTRY_IMAGE}/ci:latest
    - docker push ${CI_REGISTRY_IMAGE}/ci:latest

##########################
### Docker             ###
##########################
lint-docker:
  stage: lint
  script:
    - hadolint docker.Dockerfile

build-docker:
  stage: build
  script:
    - docker pull ${CI_REGISTRY_IMAGE}/docker:latest || true
    - docker build --cache-from ${CI_REGISTRY_IMAGE}/docker:latest -t ${CI_REGISTRY_IMAGE}/docker:${CI_COMMIT_SHA} -f docker.Dockerfile .
    - docker push ${CI_REGISTRY_IMAGE}/docker:${CI_COMMIT_SHA}

publish-docker:
  stage: publish
  only: [ master ]
  script:
    - docker pull ${CI_REGISTRY_IMAGE}/docker:${CI_COMMIT_SHA}
    - docker tag ${CI_REGISTRY_IMAGE}/docker:${CI_COMMIT_SHA} ${CI_REGISTRY_IMAGE}/docker:latest
    - docker push ${CI_REGISTRY_IMAGE}/docker:latest
