image: docker:stable

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

before_script:
  - docker login -u ${CI_REGISTRY_USER} -p ${CI_JOB_TOKEN} ${CI_REGISTRY}

stages:
  - lint
  - build
  - publish

lint-ci:
  stage: lint
  script:
    - echo "true"
    # - docker pull hadolint/hadolint
    # - docker run --rm -i hadolint/hadolint < ci.Dockerfile

build-ci:
  stage: build
  script:
    - docker pull ${CI_REGISTRY_IMAGE}/ci:latest || true
    - docker build --cache-from ${CI_REGISTRY_IMAGE}/ci:latest -t ${CI_REGISTRY_IMAGE}/ci:${CI_COMMIT_SHA} -f ci.Dockerfile .
    - docker push ${CI_REGISTRY_IMAGE}/ci:${CI_COMMIT_SHA}

publish-ci:
  stage: publish
  only: [ master ]
  script:
    - docker pull ${CI_REGISTRY_IMAGE}/ci:${CI_COMMIT_SHA}
    - docker tag ${CI_REGISTRY_IMAGE}/ci:${CI_COMMIT_SHA} ${CI_REGISTRY_IMAGE}/ci:latest
    - docker push ${CI_REGISTRY_IMAGE}:latest
