#!/bin/sh

# Set the keys we will use to assume the role
export AWS_ACCESS_KEY_ID="$AUTH_AWS_ACCESS_KEY_ID"
export AWS_SECRET_ACCESS_KEY="$AUTH_AWS_SECRET_ACCESS_KEY"

# Assume the role
CREDS=$(aws sts assume-role --role-arn "${1}" --role-session-name atlantis | jq -r '.Credentials')
akid=$(echo "$CREDS" | jq -r '.AccessKeyId')
sak=$(echo "$CREDS" | jq -r '.SecretAccessKey')
st=$(echo "$CREDS" | jq -r '.SessionToken')

# Export the assume role variables
export AWS_ACCESS_KEY_ID="$akid"
export AWS_SECRET_ACCESS_KEY="$sak"
export AWS_SESSION_TOKEN="$st"
export AWS_SECURITY_TOKEN="$st"
