repos:
  - id: /.*/
    allowed_overrides: [workflow]
    apply_requirements: [approved, mergeable]

workflows:
  default:
    plan:
      steps:
        - init
        - plan
    apply:
      steps:
        - apply
  aws:
    plan:
      steps:
        - run: source assume-role $(cat atlantis-role-arn) && terraform init -input=false -no-color
        - run: source assume-role $(cat atlantis-role-arn) && terraform plan -input=false -refresh -no-color -out $PLANFILE
    apply:
      steps:
        - run: source assume-role $(cat atlantis-role-arn) && terraform apply -no-color $PLANFILE
