name: Build/Push CI Image PRs

on: pull_request

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Code - Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Docker - Login
        run: docker login docker.pkg.github.com -u lingrino -p ${DOCKER_LOGIN_TOKEN}
        env:
          DOCKER_LOGIN_TOKEN: ${{ secrets.DOCKER_LOGIN_TOKEN }}
      - name: Docker - Pull Latest
        run: docker pull docker.pkg.github.com/${GITHUB_REPOSITORY}/ci:latest | true
      - name: Docker - Build
        run: docker build --cache-from docker.pkg.github.com/${GITHUB_REPOSITORY}/ci:latest -t docker.pkg.github.com/${GITHUB_REPOSITORY}/ci:${GITHUB_SHA} -f ci.Dockerfile .
      - name: Docker - Push
        run: docker push docker.pkg.github.com/${GITHUB_REPOSITORY}/ci:${GITHUB_SHA}
