name: Build & Push CI Image PRs

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    container: lingrino/ci:latest
    steps:
      - name: Code - Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Lint
        run: hadolint --config /root/.config/hadolint.yaml ci.Dockerfile
  build-and-push:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Code - Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Set Timestamp
        run: echo "$(date +%s)" > "${GITHUB_WORKSPACE}/timestamp.txt"
      - name: Docker - Login
        run: echo "${DOCKER_HUB_TOKEN}" | docker login -u lingrino --password-stdin
        env:
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Docker - Pull Latest
        run: docker pull "lingrino/ci:latest" || true
      - name: Docker - Build
        run: |
          docker build \
            --cache-from "lingrino/ci:latest" \
            -t "lingrino/ci:${GITHUB_SHA}" \
            -t "lingrino/ci:$(cat "${GITHUB_WORKSPACE}/timestamp.txt")" \
            -f ci.Dockerfile .
      - name: Docker - Push
        run: |
          docker push "lingrino/ci:${GITHUB_SHA}"
          docker push "lingrino/ci:$(cat "${GITHUB_WORKSPACE}/timestamp.txt")"
