name: Build & Push Docker Image Master

on:
  push:
    branches:
      - master
  schedule:
    - cron: 0 16 * * 1 # Every Monday at 4pm UTC

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Code - Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Set Timestamp
        run: echo "$(date +%s)" > "${GITHUB_WORKSPACE}/timestamp.txt"
      - name: Docker - Login
        run: echo "${DOCKER_HUB_PASSWORD}" | docker login -u lingrino --password-stdin
        env:
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Docker - Pull Latest
        run: docker pull "lingrino/docker:latest" || true
      - name: Docker - Build
        run: |
          docker build \
            --cache-from "lingrino/docker:latest" \
            -t "lingrino/docker:${GITHUB_SHA}" \
            -t "lingrino/docker:$(cat "${GITHUB_WORKSPACE}/timestamp.txt")" \
            -t "lingrino/docker:latest" \
            -f docker.Dockerfile .
      - name: Docker - Push
        run: |
          docker push "lingrino/docker:${GITHUB_SHA}"
          docker push "lingrino/docker:$(cat "${GITHUB_WORKSPACE}/timestamp.txt")"
          docker push "lingrino/docker:latest"
