name: Build & Push CI Image Master

on:
  push:
    branches:
      - master
  schedule:
    - cron: 0 16 * * 1 # Every Monday at 4pm UTC

jobs:
  lint:
    runs-on: ubuntu-latest
    container: lingrino/ci:latest
    steps:
      - name: Code - Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Lint
        run: hadolint --config /root/.config/hadolint.yaml ci.Dockerfile
  build-and-push:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Code - Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Set Timestamp
        run: echo "$(date +%s)" > "${GITHUB_WORKSPACE}/timestamp.txt"
      - name: Docker - Login
        run: echo "${DOCKER_HUB_PASSWORD}" | docker login -u lingrino --password-stdin
        env:
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Docker - Pull Latest
        run: docker pull lingrino/ci:latest || true
      - name: Docker - Build
        run: |
          docker build \
            --cache-from "lingrino/ci:latest" \
            -t "lingrino/ci:${GITHUB_SHA}" \
            -t "lingrino/ci:$(cat "${GITHUB_WORKSPACE}/timestamp.txt")" \
            -t "lingrino/ci:latest" \
            -f docker.Dockerfile .
      - name: Docker - Push
        run: |
          docker push "lingrino/ci:${GITHUB_SHA}"
          docker push "lingrino/ci:$(cat "${GITHUB_WORKSPACE}/timestamp.txt")"
          docker push "lingrino/ci:latest"
