name: Build & Push Docker Image PRs

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    container: lingrino/ci:latest
    steps:
      - name: Code - Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Lint
        run: hadolint --config /root/.config/hadolint.yaml docker.Dockerfile
  build-and-push:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Code - Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Set Timestamp
        run: echo "$(date +%s)" > "${GITHUB_WORKSPACE}/timestamp.txt"
      - name: Docker - Login
        run: echo "${DOCKER_HUB_PASSWORD}" | docker login -u lingrino --password-stdin
        env:
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Docker - Pull Latest
        run: docker pull "lingrino/docker:latest" || true
      - name: Docker - Build
        run: |
          docker build \
            --cache-from "lingrino/docker:latest" \
            -t "lingrino/docker:${GITHUB_SHA}" \
            -t "lingrino/docker:$(cat "${GITHUB_WORKSPACE}/timestamp.txt")" \
            -f docker.Dockerfile .
      - name: Docker - Push
        run: |
          docker push "lingrino/docker:${GITHUB_SHA}"
          docker push "lingrino/docker:$(cat "${GITHUB_WORKSPACE}/timestamp.txt")"
