name: Repo - Validate

on:
  - push

jobs:
  validate:
    runs-on: ubuntu-latest
    container: lingrino/ci:latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: License Exists
        run: test -f LICENSE
      - name: Readme Exists
        run: test -f README.md
      - name: Readme Lint
        run: markdownlint README.md
      - name: Gitignore Exists
        run: test -f .gitignore
